export class Constants {
  static readonly DATABASE_NAME = 'browser.db';
  static readonly DATABASE_VERSION = 1;
  static readonly TABLE_BOOKMARKS = 'bookmarks';
  static readonly TABLE_HISTORY = 'history';
  static readonly DEFAULT_SEARCH_ENGINE = 'https://www.bing.com/search?q=';
  static readonly HOME_PAGE = 'https://www.bing.com';
  static readonly BOOKMARK_FOLDER_DEFAULT = '默认';
  static readonly MAX_HISTORY_ITEMS = 500;
}
